apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: nextcloud
type: Opaque
data:
  password: cGFzc3dvcmQ=  # 'password' en base64 (cambia 'password' por tu propia contraseña y codifícala en base64)
